// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nudge.Data;

#nullable disable

namespace Nudge.Data.Migrations
{
    [DbContext(typeof(NudgeDbContext))]
    partial class NudgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Nudge.Data.Entities.TableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DisplayYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FileLastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilenameManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilenameTagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilenameTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilenameYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableInfoAuthorEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableInfoAuthorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableInfoAuthorWebSite")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableInfoBlurb")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableInfoDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableInfoReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableInfoRules")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableInfoTableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableInfoVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayTitle");

                    b.HasIndex("InstallationId", "FilePath")
                        .IsUnique();

                    b.ToTable("Tables", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
